### ISSUE TITLE
dangerous/blocked link from home page

### ISSUE THREAD

**Issue by evavanrooijen** [wisdombeyonddata/wisdombeyonddata.github.io#7]
If you click on the link on the home page to visit the blog page, you get a blocked message saying we are trying to steal password..... shitty

![image](https://user-images.githubusercontent.com/36630188/107620866-afa86200-6c55-11eb-86a7-0a14d0825fa2.png)

**Comment by s-navya-1998** [comment]
Lmaooo I just got that 2 seconds ago

**Comment by evavanrooijen** [comment]
deleted the link, easy but working solution!
